### POST request to User API
POST http://localhost:8000/api/User
Content-Type: application/json

{
    "name": "John Doe"
}

###

GET http://localhost:8000/api/user

###

GET http://localhost:8000/api/user/1

###

PUT http://localhost:8000/api/user/1
Content-Type: application/json

{
    "name": "Updated John Doe"
}

###

DELETE http://localhost:8000/api/user/1

###