### POST request to SalesOffer API
POST http://localhost:8000/api/SalesOffer
Content-Type: application/json

{
    "name": "John Doe"
}

###

GET http://localhost:8000/api/salesoffer

###

GET http://localhost:8000/api/salesoffer/1

###

PUT http://localhost:8000/api/salesoffer/1
Content-Type: application/json

{
    "name": "Updated John Doe"
}

###

DELETE http://localhost:8000/api/salesoffer/1

###