### POST request to Client API
POST http://localhost:8000/api/Client
Content-Type: application/json

{
    "name": "John Doe"
}

###

GET http://localhost:8000/api/client

###

GET http://localhost:8000/api/client/1

###

PUT http://localhost:8000/api/client/1
Content-Type: application/json

{
    "name": "Updated John Doe"
}

###

DELETE http://localhost:8000/api/client/1

###